### ISSUE TITLE
Unknown mods in the ExcludeMods setting causes server to fail to start

### ISSUE THREAD

**Issue by djmattyg007** [Lupicus/VendingMachine#1]
If an unknown mod is in the list of the `ExcludeMods` setting, a Minecraft Forge 1.15.2-31.2.36 server will fail to start. Removing mods from this list that are not installed resolves the issue.

**Comment by Lupicus** [comment]
I created a server with that version and it starts fine. I also connected to it without a problem. I saw the Unknown mods reported in the log file as they should be.
Can you provide some more info?

**Comment by djmattyg007** [comment]
I can try to get you a stack trace if you want, but it was rather non-descript.

**Comment by Lupicus** [comment]
Sure anything that can help

**Comment by Lupicus** [comment]
Never seen it happen and no further details given, also the workaround is to remove entries for mods not loaded, so closing this issue.
