### ISSUE TITLE
Curious vm default config: "ExcludeItems=[..." , #minecraft:trim_templates", "-minecraft:coast_armor..."

### ISSUE THREAD

**Issue by markygnlg** [Lupicus/VendingMachine#13]
VendingMachine-1.20-1.0.10.jar for mc v1.20.1:

 - vm-common.toml states:

#Exclude Items
ExcludeItems = [ ... "minecraft:netherite_upgrade_smithing_template", "#minecraft:trim_templates", "-minecraft:coast_armor_trim_smithing_template", ... ] 

I'm not sure if "#minecraft" &/or "-minecraft" is correct in the default config/toml file.

I am using minecraft 1.20.1.

**Comment by Lupicus** [comment]
They are correct. The # prefix is a tag item group, in this case was all the trim templates for armor defined by minecraft, but I wanted to allow getting one of them, so the - prefix allows removing items from the exclude list.

**Comment by markygnlg** [comment]
Thanks, that's good to know!
