### ISSUE TITLE
regarding the issue of expenses

### ISSUE THREAD

**Issue by opierice** [Lupicus/VendingMachine#14]
how can I make the trade cost random?

**Comment by Lupicus** [comment]
currently, there are no random cost. Fixed mode allows custom costs, but the default used is based on item rarity.
In terms of random trade costs are you wanting to be able to define a set of costs for each type of rarity and one is picked randomly or just not use rarity system?

**Comment by opierice** [comment]
umm.. in fact, I think the rarity system is good, but I want to separately configure special prices for some items in my server

**Comment by Lupicus** [comment]
so not really random costs, but custom item costs. So, something like an elytra for 2 nether stars and other items not defined fallback to rarity costs? Are you wanting 2 item costs like an elytra for 1 nether star and 1 book?

**Comment by opierice** [comment]
yep bro

**Comment by Lupicus** [comment]
Added a custom item cost system which it will use first and if not there it will use the rarity system
