### ISSUE TITLE
1.18.2 Random not restocking

### ISSUE THREAD

**Issue by rexzooly** [Lupicus/VendingMachine#8]
Hey there, I have it set to random and fixed to false but no matter what we do the new day does not seem to restock with new items in to te vm this also seems to be the case with user placed ones.

I don't seem to get any errors in the logs and never had this problem in 1.16.5 could you think of something that could affect this?

I used the vanilla settings file and 
https://gist.github.com/rexzooly/ff81042d5504e3d871cc4b0ec8ee511b

**Comment by rexzooly** [comment]
Did a little more testing I even got all the times of one item so it would hit 0 and it wont even restock that, it seems if you sleep it's not triggering it I am going to stay up all night this time and test it again see if full day/night will reset it.

**Comment by rexzooly** [comment]
If you don't sleep it seems to reset this isn't how it used to work for me and my wife so was it bugged for us last time we used it or this time?

**Comment by Lupicus** [comment]
I tried latest 1.18.2 and 1.0.0.7 version of the mod. Sleeping reset the trades for me. Maybe another mod is causing this problem.

**Comment by Lupicus** [comment]
You can check that the day increases by 1 after sleeping by looking on debug screen at the end of Local difficulty.

**Comment by rexzooly** [comment]
Sorry I forgot to reply to this, it seems a vote sleep mod was created wrong and was skipping the night rather then sleeping though the night there for braking your mod.
